apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name              tail
        Tag               user-static-apps.*
        Path              /logs/user-static-apps/*.log
        Parser            custom_log
        DB                /var/log/flb_user_static_apps.db
        Buffer_Chunk_Size 32KB
        Buffer_Max_Size   1MB      
        Mem_Buf_Limit     2MB
        Skip_Long_Lines   On

    [FILTER]
        Name                kubernetes
        Match               user-static-apps.*
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

    [OUTPUT]
        Name            http
        Match           user-static-apps.*
        Host            host.k3d.internal   
        Port            8000
        URI             /apis/v1/log
        Header          Content-Type application/json
        Header          X-Api-Key  <your-api-key-here>
        Format          json
        Json_date_key   timestamp
        Json_date_format iso8601
        tls             Off

  parsers.conf: |
    [PARSER]
        Name         custom_log
        Format       regex
        Regex        \[(?<envId>[^\]]+)\] \[(?<timestamp>[^\]]+)\] \[(?<type>[^\]]+)\] \[(?<level>[^\]]+)\]: (?<message>.*)
        Time_Key     timestamp
        Time_Format  %Y-%m-%dT%H:%M:%SZ

