apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dynamic-apps-restrict
  namespace: user-dynamic-apps
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: prod-services
          podSelector:
            matchLabels:
              app: gateway
              
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: prod-services
          podSelector:
            matchLabels:
              app: ingress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: prod-services
          podSelector:
            matchLabels:
              app: gateway

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    - to:
        - ipBlock:
            cidr: 0.0.0.0/0

