openapi: 3.0.3
info:
  title: GitHub Service API
  description: GitHub integration service for managing repositories and installations
  version: 1.0.0

servers:
  - url: http://localhost:8000/apis/v1/github
    description: Development server
  - url: https://api.shipoff.in/apis/v1/github
    description: Production server

security:
  - BearerAuth: []

paths:
  /repos:
    get:
      tags:
        - GitHub Repositories
      summary: Get a list of GitHub repositories
      description: Retrieve a list of repositories from GitHub
      security: []
      responses:
        '200':
          description: Webhook processed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: Repo fetched successfully
                  res:
                    type: array
                    items:
                      $ref: '#/components/schemas/GithubRepo'
        '400':
          description: Bad request - Invalid payload or signature
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid signature
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity - Unsupported event type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /repos/{repoId}:
    get:
      tags:
        - GitHub Repositories
      summary: Get a specific GitHub repository
      description: Retrieve details of a specific repository by its ID
      security: []
      parameters:
        - name: repoId
          in: path
          required: true
          description: The ID of the GitHub repository
          schema:
            type: string
      responses:
        '200':
          description: Repository details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: Repo fetched successfully
                  res:
                    $ref: '#/components/schemas/GithubRepo'
        '400':
          description: Bad request - Invalid repository ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found - Repository does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /installation:
    get:
      tags:
        - GitHub Installation
      summary: Get GitHub installation details
      description: Retrieve details of the GitHub installation
      security: []
      responses:
        '200':
          description: Installation details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: Installation fetched successfully
                  res:
                    $ref: '#/components/schemas/GithubInstallation'
        '404':
          description: Not Found - Installation does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    GithubRepo:
      type: object
      properties:
        githubRepoId:
          type: string
        githubRepoFullName:
          type: string
        githubRepoName:
          type: string
        githubRepoURI:
          type: string
        githubRepoDefaultBranch:
          type: string
        githubRepoPrivate:
          type: boolean
    GithubInstallation:
      type: object
      properties:
        githubInstallationId:
          type: string
        userId:
          type: string
        githubUserName:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
          example: Error message
        res:
          type: object
          nullable: true