openapi: 3.0.3
info:
  title: Orchestrator Service API
  description: Container orchestration service for managing build and production containers
  version: 1.0.0

servers:
  - url: http://localhost:8000/apis/v1/orchestrator
    description: Development server
  - url: https://api.shipoff.in/apis/v1/orchestrator
    description: Production server

security:
  - BearerAuth: []

paths:
  /containers/repo/clone-uri:
    get:
      tags:
        - Container Management
      summary: Get repository clone URI
      description: Get the clone URI for repository access with authentication
      responses:
        '200':
          description: Clone URI retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloneURIResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Repository not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  # Internal service endpoints (not exposed via gateway)
  /containers:
    get:
      tags:
        - Internal Container Operations
      summary: Get container by domain (Internal)
      description: Internal endpoint to get container information by domain
      security: []
      parameters:
        - name: domain
          in: query
          required: true
          description: Container domain
          schema:
            type: string
            example: myapp.example.com
      responses:
        '200':
          description: Container retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContainerResponse'
        '404':
          description: Container not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /containers/{type}/creds:
    get:
      tags:
        - Container Management
      summary: Get container credentials
      description: Get environment variables and credentials for build or production containers
      parameters:
        - name: type
          in: path
          required: true
          description: Container type (build or prod)
          schema:
            type: string
            enum: [build, prod]
            example: build
      responses:
        '200':
          description: Container credentials retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContainerCredsResponse'
        '400':
          description: Bad request - Invalid container type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Container not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Container:
      type: object
      properties:
        containerId:
          type: string
          example: "container_123456"
        name:
          type: string
          example: "my-app-container"
        domain:
          type: string
          example: "myapp.example.com"
        status:
          type: string
          example: "running"
          enum: [running, stopped, building, failed, pending]
        projectId:
          type