apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    # ---------- INPUTS ----------
    # User namespaces (static + dynamic apps) → custom API
    [INPUT]
        Name              tail
        Tag               user-apps.*
        Path              /var/log/containers/*_user-static-apps_*.log,/var/log/containers/*_user-dynamic-apps_*.log
        DB                /fluent-bit/state/flb_user_apps.db 
        Buffer_Chunk_Size 32KB
        Buffer_Max_Size   1MB      
        Mem_Buf_Limit     2MB
        Skip_Long_Lines   On
        Refresh_Interval  10

    # prod-services namespace → Loki
    [INPUT]
        Name              tail
        Tag               prod-services.*
        Path              /var/log/containers/*_prod-services_*.log
        multiline.parser  docker,prod_services_multiline
        DB                /fluent-bit/state/flb_prod_services.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

    # ---------- FILTERS ----------
    # Kubernetes enrichment for user apps
    [FILTER]
        Name                kubernetes
        Match               user-apps.*
        Merge_Log           On
        Keep_Log            On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Labels              On
        Annotations         On

    # Kubernetes enrichment for prod-services
    [FILTER]
        Name                kubernetes
        Match               prod-services.*
        Merge_Log           Off
        Keep_Log            On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Labels              On
        Annotations         On

    # Parse the structured fields from prod-services logs
    [FILTER]
        Name              parser
        Match             prod-services.*
        Key_Name          log
        Parser            prod_services_log_fields
        Reserve_Data      On
        Preserve_Key      Off

    # Add labels for Loki
    [FILTER]
        Name              modify
        Match             prod-services.*
        Add               job prod-services
        Add               cluster k3s

    # Parse custom logs for user apps
    [FILTER]
        Name              parser
        Match             user-apps.*
        Parser            custom_log
        Key_Name          log
        Reserve_Data      On

    [FILTER]
        Name              record_modifier
        Match             user-apps.*
        Whitelist_key     timestamp
        Whitelist_key     envId
        Whitelist_key     type
        Whitelist_key     level
        Whitelist_key     message

    # ---------- OUTPUTS ----------
    # User namespaces → custom API
    [OUTPUT]
        Name            http
        Match           user-apps.*
        Host            gateway.prod-services.svc.cluster.local
        Port            80
        URI             /apis/v1/log
        Header          Content-Type application/json
        Header          X-Api-Key <YOUR_API_KEY_HERE>
        Format          json
        Json_date_key   timestamp
        Json_date_format iso8601
        tls             Off
        Retry_Limit     3

    # prod-services → Grafana Loki
    [OUTPUT]
        Name                loki
        Match               prod-services.*
        Host                logs-prod-028.grafana.net
        Port                443
        tls                 on
        tls.verify          on
        http_user           1350969
    http_passwd         <YOUR_API_SECRET_HERE>
        labels              job=prod-services,cluster=k3s
        label_keys          $service,$level,$rid

  parsers.conf: |
    [PARSER]
        Name         custom_log
        Format       regex
        Regex        \[(?<envId>[^\]]+)\] \[(?<timestamp>[^\]]+)\] \[(?<type>[^\]]+)\] \[(?<level>[^\]]+)\]: (?<message>.*)
        Time_Key     timestamp
        Time_Format  %Y-%m-%dT%H:%M:%SZ

    [MULTILINE_PARSER]
        Name          prod_services_multiline
        Type          regex
        Flush_timeout 1000
        Rule      "start_state"   "^\[(?<timestamp>[^\]]+)\] \[(?<service>[^\]]+)\] (?<level>\w+): \[rid:(?<rid>[^\]]+)\]: (?<message>.*)"   "cont"
        Rule      "cont"          "^(?!\[).*"   "cont"

    [PARSER]
        Name         prod_services_log_fields
        Format       regex
        Regex        ^\[(?<timestamp>[^\]]+)\] \[(?<service>[^\]]+)\] (?<level>\w+): \[rid:(?<rid>[^\]]+)\]: (?<message>.*)
        Time_Key     timestamp
