apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: prod-services
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: shipoff/shipoff-services:gateway-1.0.0
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: gateway-env
            - secretRef:
                name: general-env
            - secretRef:
                name: service-url-env
          resources:
            requests:
              memory: 500Mi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 500m
      imagePullSecrets:
        - name: shipoff-registry-secret
        
---

apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: prod-services
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
  type: NodePort
